import type { Config } from 'jest';

const config: Config = {
  moduleFileExtensions: ['js', 'json', 'ts'],
  rootDir: '.',
  testRegex: '.*\\.spec\\.ts$',
  transform: {
    '^.+\\.(t|j)s$': 'ts-jest',
  },
  collectCoverageFrom: [
    'src/common/prisma.service.ts',
    'src/common/security/decrypt-payload.pipe.ts',
    'src/common/security/encrypted-validation.pipe.ts',
    'src/common/security/payload-crypto.ts',
    'src/modules/auth/auth.module.ts',
    'src/modules/auth/jwt-auth.guard.ts',
    'src/modules/auth/roles.decorator.ts',
    'src/modules/auth/roles.guard.ts',
    'src/modules/chat/chat.controller.ts',
    'src/modules/chat/chat.dto.ts',
    'src/modules/chat/chat.module.ts',
    'src/modules/clients/clients.dto.ts',
    'src/modules/clients/clients.module.ts',
    'src/modules/dashboard/dashboard.controller.ts',
    'src/modules/dashboard/dashboard.module.ts',
    'src/modules/notifications/notifications.controller.ts',
    'src/modules/notifications/notifications.dto.ts',
    'src/modules/notifications/notifications.module.ts',
    'src/modules/payments/payments.controller.ts',
    'src/modules/payments/payments.dto.ts',
    'src/modules/payments/payments.module.ts',
    'src/modules/pricing/pricing.controller.ts',
    'src/modules/pricing/pricing.dto.ts',
    'src/modules/pricing/pricing.module.ts',
    'src/modules/products/products.controller.ts',
    'src/modules/products/products.module.ts',
    'src/modules/queue/queue.module.ts',
    'src/modules/storage/storage.port.ts',
    'src/modules/storage/storage.tokens.ts',
    'src/modules/tasks/tasks.controller.ts',
    'src/modules/tasks/tasks.dto.ts',
    'src/modules/tasks/tasks.module.ts',
    'src/modules/tasks/application/tasks.repository.ts',
    'src/modules/tasks/application/tasks.service.ts',
    'src/modules/users/users.dto.ts',
    'src/modules/users/users.module.ts',
    'src/modules/users/users.service.ts',
  ],
  coverageThreshold: {
    global: {
      branches: 99,
      functions: 99,
      lines: 99,
      statements: 99,
    },
  },
  coverageDirectory: 'coverage',
  testEnvironment: 'node',
};

export default config;
